---
title: "2b_Additional module"
author: "Lawson et al"
date: "2023-07-13"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = F)

options(scipen=999)

library(tidyverse)
library("ggsci")
library(here)
library(knitr)
library(stargazer)

rm(list = ls())
```

## Modify original model to include other counterfactuals

```{r, load results}

result1 = read.csv(here('data', 'outputs', 'result1.csv'))
calibration = read.csv(here("data", 'outputs', "calibration_params.csv"))

for(i in 1:nrow(calibration)){
  assign(calibration$params[i], calibration$value[i])
}  
```

### Include Open Access equilibrium

Using equation 3 in Section 2.1 of the Supplementary materials : 

```{r, open access}
open_access = function(x){
  y = ((alpha - c)*sigma^2*x^2)/(2*W_mid + beta*sigma^2*x^2)
  return(y)
}
result1 = result1 %>% mutate(open_access = open_access(x))
```

### Include Harvest when there is aquaculture, and there is a price taking trader

```{r, aquaculture & trader}
result1 = result1 %>%
  mutate(comp_aqua = (v-c)*sigma^2*x^2/(4*W_mid))
```

### Include harvest when there is aquaculture and open access
```{r, aquaculture & oa}
result1 = result1 %>%
  mutate(oa_aqua = (v-c)*sigma^2*x^2/(2*W_mid))
```

## Graphical outputs
```{r, data processing}
for_graph = result1 %>%
  select(x,
         growth, 
         monop_harvest, 
         pt_harvest, 
         cournot_harvest, 
         bertrand_harvest, 
         oa_aqua, 
         open_access,
         comp_aqua)%>%
  pivot_longer(cols = -c(x),
               names_to = 'names',
               values_to = 'values')

set1 = function(x){
  if(x %in% c('monop_harvest', 'open_access', 'pt_harvest')){
    return('baseline')
  }else{
    return('After policy')
  }
}

set2 = function(x){
  if(x %in% c('pt_harvest', 'comp_aqua')){
    return('Competitive end market')
  }else if(x %in% c('monop_harvest', 'cournot_harvest', 'betrand_harvest')){
    return('Cartel controls upstream and downstream')
  }else if(x %in% c('oa_aqua', 'open_access')){
    return('Open access')
  }
}
  
for_graph = for_graph %>%
  mutate(set1 = sapply(names, set1), 
         set2 = sapply(names, set2))

```


```{graphs}

color1 = 'red'
color2 = 'blue'
color3 = 'seagreen3'

for_graph %>%
  ggplot(aes(x=x, y= values, colour = names))+
  geom_line()

## Both graphs present baseline and post policy outcomes
for_graph %>%
  filter(set1 == 'baseline' | names == 'growth')%>%
  ggplot(aes(x=x, y= values, colour= names))+
  geom_line(linewidth = 1)+
  theme_bw()+
  scale_color_manual(values = c('black', color1, color2, color3))

for_graph %>%
  filter(set1 == 'After policy' | names == 'growth')%>%
   ggplot(aes(x=x, y= values, colour= names))+
  geom_line()+
  theme_bw()+
  scale_color_manual(values = c(color1, color3, color1,'black', color2 ))

result1 %>%
  ggplot(aes(x = x))+
  geom_line(aes(y = growth), linewidth = 1)+
  geom_line(aes(y = monop_harvest, colour = 'Monopoly'), linewidth = 1)+
  geom_line(aes(y = cournot_harvest, colour = 'Cournot'), linetype = 2, linewidth  =1 )+
  geom_line(aes(y = bertrand_harvest, colour = 'Betrand'), linetype = 4, linewidth = 1)+
  theme_bw()+
  scale_color_manual(values = c(color1, color1, color1))


# Baseline graph : 
result1 %>%
  ggplot(aes(x = x))+
  geom_line(aes(y = growth), linewidth = 1)+
  geom_line(aes(y = monop_harvest, colour = 'Trader has full control over markets'), linewidth = 1)+
  geom_line(aes(y = open_access, colour = 'Open access fishery'), linewidth = 1)+
  geom_line(aes(y = pt_harvest, colour = 'Trader sells on competitive market'), linewidth = 1)+
  theme_bw()+
  ylab('Growth / harvest')+
  xlab('Population stock')+
  labs(colour = ' ')+
  theme(legend.position = 'bottom')+
  scale_color_manual(values = c(color1, color2, color3, 'black'))

# After graph
result1 %>%
  ggplot(aes(x = x))+
  geom_line(aes(y = growth), linewidth = 1)+
  geom_line(aes(y = cournot_harvest, colour = 'Trader competes in quantity '), linewidth = 1)+
  geom_line(aes(y = bertrand_harvest, colour = 'Trader competes in prices'), linewidth = 1)+
  geom_line(aes(y = comp_aqua, colour = 'Trader competes on competitive market'), linewidth = 1)+
    geom_line(aes(y = oa_aqua, colour = 'Open access fishery competes on competitive market'), linewidth = 1)+
  theme_bw()+
  ylab('Growth / harvest')+
  xlab('Population stock')+
  ylim(0,1250)+
  labs(colour = ' ')+
  guides(color=guide_legend(nrow=2,byrow=TRUE))+
  theme(legend.position = 'bottom')+
  scale_color_manual(values = c(color1, color2, color2, color3, 'black'))

# By market structure
  result1 %>%
    ggplot(aes(x = x))+
    geom_line(aes(y = growth), linewidth = 1)+
    geom_line(aes(y = cournot_harvest, colour = 'Trader competes in quantity '), linetype = 4, linewidth = 1)+
    geom_line(aes(y = bertrand_harvest, colour = 'Trader competes in prices'),linetype = 2, linewidth = 1)+
  geom_line(aes(y = monop_harvest, colour = 'Trader has full market control'), linewidth = 1)+
  theme_bw()+
  ylab('Growth / harvest')+
  xlab('Population stock')+
  labs(colour = ' ')+
  guides(color=guide_legend(nrow=2,byrow=TRUE))+
  theme(legend.position = 'bottom')+
  scale_color_manual(values = c('darkblue','turquoise', color2, 'black'))
  
  result1 %>%
    ggplot(aes(x = x))+
    geom_line(aes(y = growth), linewidth = 1)+
    geom_line(aes(y = open_access, colour = 'Open access fishery'), linewidth = 1)+
    geom_line(aes(y = oa_aqua, colour = 'Open access fishery competes with aquaculture on competitive market'), linewidth = 1)+
  theme_bw()+
  ylab('Growth / harvest')+
  xlab('Population stock')+
  labs(colour = ' ')+
  guides(color=guide_legend(nrow=2,byrow=TRUE))+
  theme(legend.position = 'bottom')+
  scale_color_manual(values = c(color1,'orange', 'black'))
  
  result1 %>%
    ggplot(aes(x = x))+
    geom_line(aes(y = growth), linewidth = 1)+
    geom_line(aes(y = pt_harvest, colour = 'Trader operates on competitive market'), linewidth = 1)+
    geom_line(aes(y = oa_aqua, colour = 'Trader competes with aquaculture on competitive market'), linewidth = 1)+
  theme_bw()+
  ylab('Growth / harvest')+
  xlab('Population stock')+
  labs(colour = ' ')+
  guides(color=guide_legend(nrow=2,byrow=TRUE))+
  theme(legend.position = 'bottom')+
  scale_color_manual(values = c(color3, 'springgreen', 'black'))
```
